version: '3.8'

services:
  image-classifier:
    build: .
    container_name: image-classifier
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
